### DISCUSSION TITLE
keyfile-json not working

### DISCUSSION THREAD

**Discussion by julio-romero** [dbt-labs/dbt-bigquery#786] [Q&A]
Hi, I get this problem when trying to connect using the keyfile_json parameter

```bash
Database Error
  ('Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [_OpenSSLErrorWithText(code=503841036, lib=60, reason=524556, reason_text=b'error:1E08010C:DECODER routines::unsupported')])
```

this is my profiles.yaml

```yaml
      keyfile_json:
        type: "{{ env_var('TYPE') }}"
        project_id: "{{ env_var('PROJECT_ID') }}"
        private_key_id: "{{ env_var('PRIVATE_KEY_ID') }}"
        private_key: "{{ env_var('PRIVATE_KEY') }}"
        client_email: "{{ env_var('CLIENT_EMAIL') }}"
        client_id: "{{ env_var('CLIENT_ID') }}"
        auth_uri: "{{ env_var('AUTH_URI') }}"
        token_uri: "{{ env_var('TOKEN_URI') }}"
        auth_provider_x509_cert_url: "{{ env_var('AUTH_PROVIDER') }}"
        client_x509_cert_url: "{{ env_var('CLIENT_CERT') }}"
```

I am using dbt=1.4.5
