### ISSUE TITLE
[ADAP-1007] [Feature] Cast dataproc batch runtime_config properties to strings

### ISSUE THREAD

**Issue by jimmyshah** [dbt-labs/dbt-bigquery#1001]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

While trying to configure Dataproc Serverless jobs via `profile.yml`, I keep getting an error unless I use quotes around each key-value pair, which doesn't match [dbt's documentation](https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup#running-python-models-on-dataproc).

What works for me:

```yml
runtime_config:
          properties:
           'spark.executor.instances': '4'
            'spark.driver.memory': '4g'
```

### Expected Behavior

According to [dbt's documentation](https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup#running-python-models-on-dataproc), Dataproc Serverless jobs can be configured in the dbt `profiles.yml`  file, without quotes. In the example provided on the site, `runtime_config` `properties` can be specified in yaml as such:

```yml
runtime_config:
          properties:
            spark.executor.instances: 3
            spark.driver.memory: 1
```

### Steps To Reproduce

1.  You have dbt python models already in your project
2.  Add runtime_config properties for serverless jobs without quotes
3.  Run your dbt-py model

### Relevant log output

```shell
Unable to parse dataproc_batch as valid batch specification. See https://cloud.google.com/dataproc-serverless/docs/reference/rpc/google.cloud.dataproc.v1#google.cloud.dataproc.v1.Batch. Failed to parse runtime_config field: Failed to parse properties field: expected string or bytes-like object..
```

### Environment

```markdown
- OS: Mac OS Sonoma 14.1
- Python: 3.9.6
- dbt-core: 1.6.2
- dbt-bigquery: 1.6.4
```

**Comment by dbeatty10** [comment]
Thanks for reporting this @jimmyshah !

Did only single quotes work for you, or did double quotes work also, like this?
```yaml
        runtime_config:
          properties:
            "spark.executor.instances": "4"
            "spark.driver.memory": "4g"
```

Does this work for you?
```yaml
        runtime_config:
          properties:
            spark.executor.instances: '4'
            spark.driver.memory: '4g'
```

Or did the `spark.executor.instances` and `spark.driver.memory` keys need to be quoted as well?

Ultimately, I'm curious if maybe only integers need to be quoted, but everything else doesn't need to be quoted?
