### ISSUE TITLE
[ADAP-1061] [Regression] Source freshness never sends query and never finishes/fail if loaded_at_field is not specified

### ISSUE THREAD

**Issue by rloredo** [dbt-labs/dbt-bigquery#1044]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

With 1.7.2 if I remove loaded_at_field in a source freshness test, it logs that it started running the freshness test but never sends the query to BigQuery nor fails.

### Expected Behavior

Fail and raise an error, or don't run that freshness test.

### Steps To Reproduce

Using dbt-bigquery 1.7.2

With a source specified as:

```
tables:
      - name: source_something
         freshness:
          error_after: { count: 1, period: hour }
          filter: something_at >= '{{ var("data_interval_start") }}'
```

Running 

`dbt source freshness`

will run forever.

In dbt-bigquery 1.6.5 it just doesn't run.

### Relevant log output

```shell
Logs show nothing.
```

### Environment

```markdown
- OS: MacOS 13.6 (22G120), Debian 11
- Python: 3.10.9
- dbt-core: 1.7.3
- dbt-bigquery: 1.7.2
```

### Additional Context

@mikealfare: Per @dbeatty10's comment:

```[tasklist]
### Tasks
- [ ] Skip any source freshness tests where `loaded_at_field` is missing (to restore behavior of 1.6)
- [ ] Raise a warning whenever `loaded_at_field` is missing
- [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/4615
```
