### ISSUE TITLE
[Bug] Table description does not updated in spite of setting persist_docs

### ISSUE THREAD

**Issue by kiwamizamurai** [dbt-labs/dbt-bigquery#1138]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Table description does not updated even thought I modify the schema.yaml with persist_docs is set true only when materialized=incremental.

### Expected Behavior

Table description should be updated regardless of materialization type.

### Steps To Reproduce

1. write the sample.sql as follows

```sample.sql
{{
  config(
    materialized = 'incremental',
    persist_docs={"relation": true, "columns": true}
  )
}}

select 1 as first_col
from unnest([struct(1 as dual)]) as dual

{% if is_incremental() %}
    where 1=1
{% endif %}
```

2. write the sample.yaml as follows

```yaml
version: 2

models:
  - name: _base_tsutsumi
    description: before_changed
    columns:
      - name: first_col
        description: before_changed
```

3. run the command `dbt build --select sample`
4. confirm that the table is created in bigquery console
5. modify the sample.yaml as follows

```yaml
version: 2

models:
  - name: _base_tsutsumi
    description: after_changed
    columns:
      - name: first_col
        description: after_changed
```

6. confirm that only the column description is updated

### Environment

```markdown
- OS: 13.6
- Python: 3.11.7
- dbt-core: 1.7.6
- dbt-bigquery: 1.7.6
```
