### ISSUE TITLE
[Bug] <BQ is not applying policies to the same object at the same time>

### ISSUE THREAD

**Issue by Lana-hl** [dbt-labs/dbt-bigquery#1167]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

BigQuery does not allow to apply policies to the same object at the same time, even if those policies have the same effect.
Error message: `500 IAM setPolicy failed for Dataset <>: There were concurrent policy changes.` 

Perhaps we would need to update how we apply and persist grants here?

### Expected Behavior

Policies could be applied concurrently to the same object at the same time.

### Steps To Reproduce

Only affects when BQ is running concurrent changes, and when running the grants separately and sequentially in the console returns a successful execution, which indicates that parallel invocations of these queries might be causing the issue.

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-bigquery:
```

**Comment by Fleid** [comment]
Hey there!
Could you help us reproduce the case? I'm wondering how you get concurrent changes here? Are you running multiple invocations of dbt in parallel?

**Comment by saahil-mehta** [comment]
Hi!
So in our CI workflow, GitHub Actions, the dbt config has 32 threads. The
error shows up when this is executed, however when threads are switched to
2 the error goes away. The multiple invocations are through GitHub Actions
workflow when deploying to production environment.


Best,
Saahil.

**Comment by Fleid** [comment]
Hi there, could you please add a [minimum reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) to the issue, so we can investigate?
You can build that out of the project generated via `dbt init`, or by tinkering with [jaffle shop](https://github.com/dbt-labs/jaffle-shop).
Thank you!

**Comment by saahil-mehta** [comment]
Hello, I find it to be a complex setup that may not be easily replicated in a smaller project or a Minimal Reproducible Example. Nonetheless, the issue is clear enough to address without simplification. Here are the specifics:

- Our dbt instance consists of over 900 models, all of which compile and build successfully when executed from the core or cloud.
- The challenge surfaces when we commit our changes to our repository.
- The GitHub Actions workflow initiates by running dependencies and building the project. During this phase, we encounter a recurring error (**IAM setPolicy failed for Dataset *:***_TABLE**: There were concurrent policy changes. Please retry the whole read-modify-write with exponential backoff. The request's ETag '\007\006\026\276r+\210+' did not match the current policy's ETag '\007\006\026\276r0\037***'.**).
- This error is linked to the model post-hooks where we specify the IAM grants:
    ```yaml
    erp:
      staging:
        materialized: ephemeral
        dataset: erp
      output:
        materialized: table
        dataset: erp  
      +grants:
        roles/bigquery.dataViewer: [
          'xx@xx.com', 
          'xx@xx.com'
        ]
      +post-hook:
        - |
          {% if target.project == 'xx' %}
            GRANT `projects/xx/roles/bigquery.selfServe` ON SCHEMA `xx`.mart_erp TO "xx@xx.com", "xx@xx.com", "xx@xx.com"
          {% endif %}
    ```
- Below is our `profiles.yml` where we specify the threads:
    ```yaml
    default:
      target: prod
      outputs:
        prod:
          type: bigquery
          method: service-account
          keyfile: xx
          project: xx
          schema: xx
          threads: 32  # this is the parameter causing the issue, if we switch this to 2, the issue goes away but the project takes 1 hour to build, in the current state it takes 9-10 mins
          location: europe-west1
          timeout_seconds: 300 ```
