### ISSUE TITLE
[Bug] persist_docs not working for seeds

### ISSUE THREAD

**Issue by dpguthrie** [dbt-labs/dbt-bigquery#1211]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The descriptions for the seed and columns are not being persisted to BQ when using the appropriate config.
```yaml
seeds:
  [<resource-path>](https://docs.getdbt.com/reference/resource-configs/resource-path):
    +persist_docs:
      relation: true
      columns: true
```

### Expected Behavior

The descriptions are populated at the object and column level for the seed in my dbt project.

### Steps To Reproduce

1. Use the yaml below to persist_docs for seeds
```yaml
seeds:
  [<resource-path>](https://docs.getdbt.com/reference/resource-configs/resource-path):
    +persist_docs:
      relation: true
      columns: true
```
2. Run `dbt seed`
3. View descriptions in BQ for that seed

This may have something to do with the size of the seed though.  From @mikealfare "It might also have something to do with the fact that tables are sharded in BQ, and we only pull the column descriptions from the most recent shard (because they can change)."

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-bigquery:
```
