### ISSUE TITLE
[Bug] Data mix-up in struct with enforced contracts

### ISSUE THREAD

**Issue by aeakoski** [dbt-labs/dbt-bigquery#1272]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When creating a materialized table with enforced contracts containing a struct type column with fields a and b using the following SQL:

```
{{ config(materialized='table') }}

select STRUCT(
    'a' AS a,
    'b' AS b
) AS bug_struct

```
and the following yaml:

```
version: 2

models:
  - name: bug_struct
    description: "A model to demo a bug struct with mixed-up fields"
    config:
      contract:
        enforced: true
    columns:
      - name: bug_struct.b
        data_type: string
      - name: bug_struct.a
        data_type: string
```

After running `dbt build` I get a table in bigquery with a struct that has its field names in the order specified in the yaml file but the struct field data in the order specified in the SQL like so:

| bug_struct.b | bug_struct.a |
|--------------|--------------|
| a            | b            |

![actual_bug](https://github.com/dbt-labs/dbt-bigquery/assets/10944194/a47bf165-cf35-41dc-b0ee-89d8e16475f2)

### Expected Behavior

With the SQL and yaml file above I expect to get the following table:

| bug_struct.b | bug_struct.a |
|--------------|--------------|
| b            | a            |

or

| bug_struct.a | bug_struct.b |
|--------------|--------------|
| a            | b            |

The most important expectation is that the corect data is under each struct field. 

![bug_expected](https://github.com/dbt-labs/dbt-bigquery/assets/10944194/7fc27fb8-5432-46af-838b-999c3b5a0fa3)

### Steps To Reproduce

1. Open your DBT project
2. Create the following bug_struct.sql:
```
{{ config(materialized='table') }}

select STRUCT(
    'a' AS a,
    'b' AS b
) AS bug_struct

```
3. Create the following schema.yml:
```
version: 2

models:
  - name: bug_struct
    description: "A model to demo a bug struct with mixed-up fields"
    config:
      contract:
        enforced: true
    columns:
      - name: bug_struct.b
        data_type: string
      - name: bug_struct.a
        data_type: string
```

4. Run `dbt build`
5. In bigquery do a `SELECT * FROM  <project_id>.schema.bug_struct` to view tha faulty table.

The faulty behavior only occurs when the table is materialized as a table and contracts are enforced.

### Relevant log output

```shell
No errors or warnings in the logs, it all looks like a successfull build.
```

### Environment

```markdown
- OS: Ubuntu and MacOS
- Python: 3.8.10
- dbt-core: 1.8.3
- dbt-bigquery: 1.8.2
```
