### ISSUE TITLE
[Bug] Reserved words cause contract enforcement query to fail

### ISSUE THREAD

**Issue by PieterBos94** [dbt-labs/dbt-bigquery#1312]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When having columns like "group" or "following" the contract enforcement query breaks because it does not use backticks "`" around the columns.

### Expected Behavior

That the reserved column names have backticks around them (`) so BigQuery doesn't give errors with reserved names while running the query that checks the contract.

### Steps To Reproduce

1. Create a model (test_following.sql):
```
SELECT
1 AS `following`,
"2" AS `group`
```

2. Create a yaml with the following config:
```
models:
  - name: test_following
    config:
      materialized: table
      contract:
        enforced: true
    columns:
    - name: following
       description: ""
      data_type: int64
      data_tests:
        - unique
        - not_null
    - name: group
       data_type: string
       description: ""
```

3. Build the model, this gives an BigQuery error since the query does not work

### Relevant log output

```shell
This is the query that is generated that fails:

select * from (
select


cast(null as int64)
as following,

cast(null as string)
as group
) as __dbt_sbq
where false and current_timestamp() = current_timestamp()
limit 0
```

### Environment

```markdown
- OS: DBT cloud
- Python:  DBT cloud
- dbt-core: Keep on latest in DBT cloud
- dbt-bigquery: 1.9.0
```

### Additional Context

I saw that another issue exists for nested columns: https://github.com/dbt-labs/dbt-bigquery/issues/1278
So probably good to fix both with the correct quoting added.
