### ISSUE TITLE
[Regression] dbt seed is not accepting custom delimiter in the seed configs

### ISSUE THREAD

**Issue by roshravoof** [dbt-labs/dbt-bigquery#1352]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

 dbt seed is not accepting custom/pipe delimiter in the seed configs

```yaml
seeds:
  - name: mappings
    config:
      delimiter: '|'
```

Above seed config doesnt work in dbt version 1.7.18

### Expected Behavior

dbt seed should accept any custom or multiple delimiters in the seed configs. dbt seed should be able to process  comma and pipe delimited files in the same project.

### Steps To Reproduce

setup dbt version 1.7.18 and python version 3.11

Setup seed config 
```yaml
seeds:
  - name: mappings
    config:
      delimiter: '|'
```

### Environment

```markdown
- Python: 3.11
- dbt: 1.7.18
```

### Which database adapter are you using with dbt?

bigquery
