### ISSUE TITLE
[Bug] Materialized views cannot be authorized

### ISSUE THREAD

**Issue by kubikb** [dbt-labs/dbt-bigquery#1471]
### Is this a new bug in dbt-bigquery?

- [x] I believe this is a new bug in dbt-bigquery
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Similarly to BigQuery views, [BigQuery materialized views can also be authorized to access the data in another dataset(s)](https://cloud.google.com/bigquery/docs/authorized-views). However, providing the `grant_access_to` configuration to a model with `materialized_view` materialization goes silently ignored and the materialized view does NOT get authorized to access data in another dataset. With models with `view` materialization, the `grant_access_to` configuration leads to the desired behavior, namely the view gets authorized to access data in another dataset.

### Expected Behavior

As per the [dbt official documentation](https://docs.getdbt.com/reference/resource-configs/bigquery-configs#authorized-views), the `grant_access_to` config can be used to "grant the view model access to select from the list of datasets provided". Similarly, one would expect dbt models with materialization set to `materialized_view` take the `grant_access_to` config and be authorized to access data in another dataset.

### Steps To Reproduce

1. Create a new or use an existing dbt project. The `dbt_project.yml` contents I used:

```

# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'materialized_view__grant'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'materialized_view__grant'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  materialized_view__grant:
    # Config indicated by + and applies to all files under models/example/
    example:
```

2. Create a test table, materialized view, and view.

`test_model.sql` contents:

```
{{ config(materialized='table') }}

with source_data as (

    select 1 as id
    union all
    select null as id

)

select *
from source_data
```

`test_materialized_view.sql` contents:

```
{{ config(
    materialized='materialized_view',
    grant_access_to=[
      {'project': '{ANOTHER_PROJECT_ID}', 'dataset': 'test_dataset'},
    ]
) }}

select
    id,
    count(1) AS count
from {{ ref('test_model') }}
group by id
```

`test_view.sql` contents:

```
{{ config(
    materialized='view',
    grant_access_to=[
      {'project': '{ANOTHER_PROJECT_ID}', 'dataset': 'test_dataset'},
    ]
) }}

select
    id,
    count(1) AS count
from {{ ref('test_model') }}
group by id
```

3. Execute `dbt run`.
4. The `test_view` becomes an authorized view, while `test_materialized_view` gets ignored and does not get authorized to access data in dataset `{ANOTHER_PROJECT_ID}.test_dataset`.

<img width="1135" alt="Image" src="https://github.com/user-attachments/assets/b13fea39-196f-46ff-a896-fcd6ec43906f" />

### Relevant log output

```shell
(env) balintkubik@Mac materialized_view__grant % dbt run         
07:10:14  Running with dbt=1.9.2
07:10:15  Registered adapter: bigquery=1.9.1
07:10:15  Unable to do partial parsing because a project config has changed
07:10:15  Found 3 models, 489 macros
07:10:15  
07:10:15  Concurrency: 1 threads (target='dev')
07:10:15  
07:10:17  1 of 3 START sql table model dbt.test_model .................................... [RUN]
07:10:24  1 of 3 OK created sql table model dbt.test_model ............................... [CREATE TABLE (2.0 rows, 0 processed) in 7.14s]
07:10:24  2 of 3 START sql materialized_view model dbt.test_materialized_view ............ [RUN]
07:10:27  2 of 3 OK created sql materialized_view model dbt.test_materialized_view ....... [None (0 processed) in 2.06s]
07:10:27  3 of 3 START sql view model dbt.test_view ...................................... [RUN]
07:10:30  3 of 3 OK created sql view model dbt.test_view ................................. [CREATE VIEW (0 processed) in 3.00s]
07:10:30  
07:10:30  Finished running 1 materialized view model, 1 table model, 1 view model in 0 hours 0 minutes and 14.07 seconds (14.07s).
07:10:30  
07:10:30  Completed successfully
07:10:30  
07:10:30  Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
```

### Environment

```markdown
- OS: MacOS 15.2 (24C101)
- Python: 3.12.5
- dbt-core: 1.9.2
- dbt-bigquery: 1.9.1
```
