### ISSUE TITLE
[CT-785] support specifying policy tag by display name

### ISSUE THREAD

**Issue by ben-marengo-msmg** [dbt-labs/dbt-bigquery#210]
### Describe the feature
i would like a model author to be able to specify a column's policy tag by its display name (eg. `CUSTOMER_EMAIL`) instead of its id (`projects/123/locations/eu/taxonomies/456/policyTags/789`)

for us, defining the taxonomy in the target would work, but perhaps the most flexible option (if people use multiple taxonomies) would be a bq-specific config:
`dbt_project.yml`
```yaml
models:
  my_project:
      taxonomy: "projects/{project_number}/locations/{location_id}/taxonomies/{taxonomy_id}"
      ...
```

`schema.yaml`
```yaml
models:
  - name: customers
    columns:
      - name: email
        policy_tag_names:  # not `policy_tags`. if `policy_tags` and `policy_tag_names` were both defined, throw error or ignore `policy_tag_names`?
          - 'PT_CUSTOMER_EMAIL'
```

### Additional context
- we have a different taxonomy of policy tags in each 'environment'. an 'environment' for us could belong to a person/team of people, or could be shared between everyone (uat/prod)
- each taxonomy has 150+ tags (defined by data governance team)

#### opt 1

maintaining policy tags [as variables](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-variables#defining-variables-in-dbt_projectyml). 

eg. `dbt_project.yml`
```yaml
vars:
  PT_CUSTOMER_EMAIL: 'projects/123/locations/eu/taxonomies/456/policyTags/789'
  PT_CUSTOMER_NAME: 'projects/123/locations/eu/taxonomies/456/policyTags/987'
  # ... +150 more
```

eg. `schema.yaml`
```yaml
models:
  - name: customers
    columns:
      - name: email
        policy_tags:
          - '{{ var('PT_CUSTOMER_EMAIL') }}'
```
initial setup for each individual user / swapping environments is a pain because all the ids change

#### opt 2 (not sure if possible?)
maybe its possible to write a macro to do the lookup, but im too noob to figure out how i could make this work?
eg. `dbt_project.yml`
```yaml
vars:
  TAXONOMY: 'projects/123/locations/eu/taxonomies/456'
```

eg. `schema.yaml`
```yaml
models:
  - name: customers
    columns:
      - name: email
        policy_tags:
          - '{{ policy_tag(var('TAXONOMY'), 'PT_CUSTOMER_EMAIL') }}'
```

### Who will this benefit?
- people who also have lots of policy tags or different taxonomies in different environments
- people who would rather see the friendly name of the policy tag, rather than the id

### Are you interested in contributing this feature?
dbt noob (not running it in prod yet), but maybe!
