### ISSUE TITLE
[CT-786] enable specifying policy tag by name instead of id

### ISSUE THREAD

**Issue by ben-marengo-msmg** [dbt-labs/dbt-bigquery#211]
### Describe the feature
enable users to specify bq policy tags by name (eg. `CUSTOMER_EMAIL`) instead of id (eg. `projects/123/locations/eu/taxonomies/456/policyTags/789`)

proposed implementation: create new bq specific configuration `taxonomy`:

`dbt_project.yml`
```yaml
models:
  my_project:
    taxonomy: 'projects/123/locations/eu/taxonomies/456'
```

`schema.yml`
```yaml
models:
  - name: customers
    columns:
      - name: email
        policy_tag_names:  # not `policy_tags`. if both specified, error? or ignore `policy_tag_names`?
          - 'CUSTOMER_EMAIL'  # would resolve to `projects/123/locations/eu/taxonomies/456/policyTags/789` when applied
```

### Additional context
- we have 150+ different policy tags
- we allow anyone to bootstrap a new 'data-platform' environment, which includes a copy of the taxonomy with all the tags. an environment could belong to a person, or be shared between a team, or anyone (uat/prod). currently we have ~50 environments

#### opt 1:

this works, but is difficult for a user to set up when they start a project and difficult to migrate projects through environments 

`dbt_project.yml`
```yaml
vars:
  PT_CUSTOMER_EMAIL: 'projects/123/locations/eu/taxonomies/456/policyTags/789'
  PT_CUSTOMER_NAME: 'projects/123/locations/eu/taxonomies/456/policyTags/987'
  ...  # +150 more
```

`schema.yml`
```yaml
models:
  - name: customers
    columns:
      - name: email
        policy_tags:
          - "{{ var('PT_CUSTOMER_EMAIL') }}"
```

#### op 2: 
im not sure if this is possible cos dbt noob...
create a mapping macro that uses the bq api to look up policy tag id?

`dbt_project.yml`
```yaml
vars:
  TAXONOMY: 'projects/123/locations/eu/taxonomies/456'
```

`schema.yml`
```yaml
models:
  - name: customers
    columns:
      - name: email
        policy_tags:
          - "{{ policy_tag(var('TAXONOMY'), 'PT_CUSTOMER_EMAIL') }}"
```

### Who will this benefit?
- people who want immediate context as to what policy tag is on each column
- people who have many taxonomies / tags

### Are you interested in contributing this feature?
not running dbt in prod yet, but possibly, yes!

**Comment by jtcohen6** [comment]
@ben-marengo-msmg Thanks for opening, and for the thoughtful writeup!

If I understand you right, the ask here is motivated by the BigQuery capability around policy tags, but it isn't a material change to the actual implementation of that capability. Instead, the ask is for for dbt to store a mapping object between human-friendly names (to be referenced elsewhere in the project), and the ID that needs to be sent to BigQuery behind the scenes.

Some mix of the proposed alternatives (opp 1 + opp 2) is what I would have in mind, leveraging existing capabilities around dbt vars + env vars. Specifically, something like:
```yaml
# dbt_project.yml
vars:
  TAXONOMY: 'projects/123/locations/eu/taxonomies/456'
  PT_CUSTOMER_EMAIL: 'policyTags/789'
  PT_CUSTOMER_NAME: 'policyTags/987'
  ...  # +150 more
```
And then:
```yaml
models:
  - name: customers
    columns:
      - name: email
        policy_tags:
          - "{{ var('TAXONOMY') ~ var('PT_CUSTOMER_EMAIL') }}"
```

The appeal of using `vars` is that the values are checked into version control, though still can be overridden via CLI flag (`--vars`). For values that are more likely to differ across environments, you could set and reference them via [`env_var`](https://docs.getdbt.com/reference/dbt-jinja-functions/env_var) instead.

Unfortunately, the specific implementation proposed in opp 2 won't work (a `policy_tag` macro), since custom macros can't be referenced within yaml file configuration today (with a few exceptions, namely hooks). I agree that feels like a more ergonomic way of "constructing" the policy tag ID, including the repeated boilerplate, so that `vars` can be responsible for just the parts that actually differ between tags/environments. That's a larger initiative, one we definitely know about, which would require nontrivial work within `dbt-core` to support. I'm inclined to close this issue for now, but record it as one more valid use case for supporting "static" macros in configuration.

For my part, I've found policy tags very very difficult to debug (#31), and I'd like to avoid baking more complex logic into `dbt-bigquery`—where it's hidden behind the scenes, and trickier for users to debug—until we have a firmer grip around the existing functionality.
