### ISSUE TITLE
[CT-1696] [Feature] Support constraints in BigQuery following the dbt Core implementation

### ISSUE THREAD

**Issue by Victoriapm** [dbt-labs/dbt-bigquery#444]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Use the new constraints configs from this PR: https://github.com/dbt-labs/dbt-core/pull/6271

```
version: 2

models:
  - name: constraints_example
    docs:
      node_color: black
    config:
      constraints_enabled: true
    columns:
      - name: id
        data_type: integer
        description: hello
        constraints: ['not null','primary key']
        check: id > 0
        tests:
          - unique
      - name: color
        data_type: string
      - name: date_day
        data_type: date
```

### Who will this benefit?

People wanting to leverage the dbt Core column constraints capability when using dbt with BigQuery

### Are you interested in contributing this feature?

yes

### Anything else?

dbt-core issues https://github.com/dbt-labs/dbt-core/issues/6079 and https://github.com/dbt-labs/dbt-core/pull/6271
