### ISSUE TITLE
[CT-2158] [Feature] Support Workload Identity Federation for Headless Authentication into BigQuery

### ISSUE THREAD

**Issue by ernestoongaro** [dbt-labs/dbt-bigquery#549]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Traditionally, applications running outside Google Cloud can use [[service account keys](https://cloud.google.com/iam/docs/service-accounts#service_account_keys)](https://cloud.google.com/iam/docs/service-accounts#service_account_keys) to access Google Cloud resources. However, service account keys are powerful credentials, and can present a security risk if they are not managed correctly.

With identity federation, you can use Identity and Access Management (IAM) to grant external identities [[IAM roles](https://cloud.google.com/iam/docs/overview#roles)](https://cloud.google.com/iam/docs/overview#roles), including the ability to impersonate service accounts. This approach eliminates the maintenance and security burden associated with service account keys.

### Describe alternatives you've considered

Oauth is fine for developer authentication, but not great for something that will be scheduling the runs (like dbt Cloud)

### Who will this benefit?

Any security-conscious GCP users 

### Anything else?

Specifically this request is for use with Azure AD (which is OIDC compliant) but there are other schemes supported:
- AWS
- Azure Active Directory
- On-premises Active Directory Federation Services (AD FS)
- Okta
- Kubernetes clusters

**Comment by ernestoongaro** [comment]
As a very good workaround to this; it is recommended that you UPLOAD service account keys 
![image](https://user-images.githubusercontent.com/47784/220599473-a573e294-4046-44fa-a8e0-a174abd335f5.png)
https://youtu.be/PAOb2hl__08?t=703

**Comment by dbeatty10** [comment]
Thanks for opening this and also supplying a "very good workaround" @ernestoongaro !

What would you imagine the `profiles.yml` entry to look like for this new connection method?


```yaml
my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: azure-ad

      # Identity federation for Azure AD auth
      some_key: [some_value]
      some_other_key: [some_other_value]
      ...
```

**Comment by dbeatty10** [comment]
We want to have a delightful experience around warehouse authentication that is friction-free, so re-opening this public-facing issue.

As @ernestoongaro mentioned, we have a separate internal ticket [here](https://dbt-labs.productboard.com/entity-detail/features/18692136) that we've kept open as well since the most significant pieces of the implementation will take place within dbt Cloud.

**Comment by b-per** [comment]
> Thanks for opening this and also supplying a "very good workaround" @ernestoongaro !
> 
> What would you imagine the `profiles.yml` entry to look like for this new connection method?
> 
> ```yaml
> my-snowflake-db:
>   target: dev
>   outputs:
>     dev:
>       type: bigquery
>       method: azure-ad
> 
>       # Identity federation for Azure AD auth
>       some_key: [some_value]
>       some_other_key: [some_other_value]
>       ...
> ```

@dbeatty10 , Workload Identity Federation is not for end user connection, but for headless/service access to resources, so Azure AD wouldn't fit in this use case.

Based on the comment you have above and [some demonstration of how WIF works with GH Actions](https://www.youtube.com/watch?v=ZgVhU5qvK1M), the profile would most likely look more like:

```yaml
my-snowflake-db:
  target: dev
  outputs:
    prod:
      type: bigquery
      method: workflow-identity-federation
      # Identity federation info
      workload_identity_provider: [some_value]
      service_account: [name_of_the_service_account]
      ...
```

On the GCP side, people would need to set a Workload Identity Pool and mention an **OpenID Connect (OIDC) provider** and its **issuer URL**.
![image](https://github.com/dbt-labs/dbt-bigquery/assets/8754100/c1c373c6-f23f-4200-80b1-6580b308cacb)

This means that we need to have a service in place that can communicate with GCP using the OIDC protocol. This would happen on the dbt Cloud side and would require some development there.

On the `dbt-bigquery` side, I will have a look at the code and identify what might need to be implemented.
