### ISSUE TITLE
[ADAP-417] Convert contract into a dict

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-bigquery#633]
Details of why this decision was made in https://github.com/dbt-labs/dbt-core/issues/7184

Convert 

```yaml
contract: true
```

to 

```yaml
contract:
  enforced: true
  <more_things_in_future>: ...
```
