### ISSUE TITLE
[CT-2416] [Feature] finer grain of `location` selection in `dbt init`

### ISSUE THREAD

**Issue by davidkhala** [dbt-labs/dbt-bigquery#668]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

When we run `dbt init` to setup a profile

There is only two option in `Desired location option`
![image](https://user-images.githubusercontent.com/7227589/231936379-d5da2f36-d0db-4b79-bc62-9d4b6a24dfd9.png)

While it is not clear to first-time user what the location value here take effect, user is APAC region feels biased about not able to select their home region. 

And evenmore, since in my case I have select bigquery as the adapter, it is intuitive that dbt can let user to select GCP region code as location input here, such as `[45] asia-east2-b`.

I expect there should be a full list of gcp zone to select during `dbt init` profile setup wizard. 

### Describe alternatives you've considered

one way is to remove this location selection step during `dbt init`, if the location isn't critial in profile. Meanwhile, as an optional settings here, we provide guideline on how to mannually set it afterwards and where it will be used. 

another way, if gcp zone is too detailed to list out, then region-grain is also acceptable like `asia-east2`

### Who will this benefit?

`dbt init` user, especially help if they start with dbt core.

### Are you interested in contributing this feature?

No

### Anything else?

If there is any document already mentioning about usage of location setting here while it is just my knowledge issue of not aware of it, please let me know.

**Comment by jtcohen6** [comment]
@davidkhala Thanks for opening - you're right, this does seem a bit limited!

[Our documentation](https://docs.getdbt.com/reference/warehouse-setups/bigquery-setup#dataset-locations) states:

> The location of BigQuery datasets can be configured using the `location` configuration in a BigQuery profile.
`location` may be either a multi-regional location (e.g. `EU`, `US`), or a regional location (e.g. `us-west2` ) as per [the BigQuery documentation](https://cloud.google.com/bigquery/docs/locations) describes.

The options provided during `dbt init` are defined here, in `profile_template.yml`:

https://github.com/dbt-labs/dbt-bigquery/blob/4673e40f36079fb547ae2a75fb352e2d0eb209ff/dbt/include/bigquery/profile_template.yml#L23-L27

We should either:
- Add more options
- Make it a free-text field

It's actually possible to override/customize this behavior for new users in your own project, by creating a `profile_template.yml` file in your project's root directory: https://docs.getdbt.com/reference/commands/init#profile_templateyml

**Comment by matty5567** [comment]
Hi @jtcohen6 

I haven't contributed before however I'm really keen to try and get involved. Wondering if this is something I could work on.

You suggested two approaches above, here are some pros and cons I see:

**Add more options**

Cons: 
- Given that there are over 30 BigQuery locations, it might be difficult to scan through and find the desired one
- If new locations are added, it requires a change to profile_template.yaml

Pros:
- Easy to implement (would just need to add these options to profile_template.yaml

**Make it free text**

Cons:
- Opens up the opportunity for spelling errors which might cause unexpected errors later down the line

Pros:
- More user friendly than a long drop down
- No changes required to profile_template.yaml if new regions are added
- Also easy to implement


**Possible 3rd approach** 

Extend the current functionality in dbt-core to allow for free text fields with limited valid responses, prompting the user to try again if the given response is invalid (possibly implemented [here](https://github.com/dbt-labs/dbt-core/blob/75703c10eecaa01549477e241e9212a66f4df40e/core/dbt/task/init.py#L103))


Let me know if you think this is something I could get involved with, thanks.

**Comment by matty5567** [comment]
Another option I was thinking about was to have multiple levels, the user could first choose the region, then the location like so:

![image](https://user-images.githubusercontent.com/56730929/234095703-469ecbd0-5275-4165-997b-532a718c3dde.png)

This can be implemented like so in profile_template.yml:
```
 _choose_region:
    Asia-Pacific:
      _choose_location:
        asia-south1:
          _fixed_location: asia-south1
        asia-south2:
          _fixed_location: asia-south2
    Americas:
      _choose_location:
        US (Multi Regional):
          _fixed_location: US
        us-west1:
          _fixed_location: us-west-1
        us-west2:
          _fixed_location: us-west-2
    Europe:
      _choose_location:
        EU (Multi Regional):
         _fixed_location: EU
        europe-west1:
          _fixed_location: europe-west1
        europe-west2:
          _fixed_location: europe-west2
```
