### ISSUE TITLE
[ADAP-503] [Regression] Persisted Metadata does not update on BigQuery tables

### ISSUE THREAD

**Issue by patricker** [dbt-labs/dbt-bigquery#687]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

After upgrading to dbt 1.5.0 column metadata does not update in BigQuery and the model build shows as failed.

### Expected Behavior

metadata writes to the tables without issue in BigQuery.

### Steps To Reproduce

1. with dbt 1.5.0, writing to BigQuery
2. Update your dbt_project:
    +persist_docs:
      relation: true
      columns: true
3. Run a model with column level documentation
4. Error received after model is fully built, during the docs persist phase.

### Relevant log output

```shell
Error: google.api_core.exceptions.BadRequest: 400 PATCH https://bigquery.googleapis.com/bigquery/v2/projects/{table_path}?prettyPrint=false: Policy tags can only be attached to a leaf field.
```

### Environment

```markdown
- OS:debian
- Python:3.9.10
- dbt:1.5.0
```

### Which database adapter are you using with dbt?

bigquery

### Additional Context

I rolled back to 1.4.6 and the issue went away.

**Comment by dbeatty10** [comment]
Thanks for reporting this @patricker and @steve-marmalade.

I was able to reproduce this when using [`policy_tags`](https://docs.getdbt.com/reference/resource-configs/bigquery-configs#policy-tags) and [`persist_docs`](https://docs.getdbt.com/reference/resource-configs/persist_docs).

**Comment by dbeatty10** [comment]
### Simple reprex

`dbt_project.yml`
```yaml
name: "my_dbt_project"
version: "1.0.0"
config-version: 2
profile: "sandcastle-bigquery"

models:
  my_dbt_project:
    +persist_docs:
      relation: true
      columns: true
```

`models/_models.yml`
```yaml
# version isn't required for dbt-core 1.5, but it is for 1.4
version: 2

models:
  - name: my_model
    columns:
      - name: id
        description: Primary key
        policy_tags:
          # Example pattern:
          # - 'projects/<gcp-project>/locations/<location>/taxonomies/<organization>/policyTags/<tag>'
          - projects/dbt-test-env/locations/us/taxonomies/5785568062805976401/policyTags/135489647357012267
```

`models/my_model.sql`
```sql
{{ config(materialized='table') }}

select 1 as id
```
