### ISSUE TITLE
[Feature] Add support for Authrorized Datasets and dataset-level grants

### ISSUE THREAD

**Issue by akerone** [dbt-labs/dbt-bigquery#711]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The ability to configure [Authorized Datasets](https://cloud.google.com/bigquery/docs/authorized-datasets) in dbt-project.yml, similarly to Authorized Views. For example, a `+grant_access_to:` where `+schema:` is also present at the same level could authorize the whole dataset rather than all individual views.

The same goes for direct grants.

### Describe alternatives you've considered

dbt currently achieves the same result although, in our opinion, a less user-friendly way. Giving permissions to every separate model becomes hell when it's time to revoke any of them. 

### Who will this benefit?

Every single BQ admin who's in any way concerned by security. It also indirectly solves #126.

**Comment by dbeatty10** [comment]
Thanks for opening this feature request @akerone !

It sounds like making the revoke process easier is your primary goal?

Did you consider an alternative using [grant config inheritance](https://docs.getdbt.com/reference/resource-configs/grants#grant-config-inheritance) in your `dbt_project.yml` similar to the following (using [BigQuery-specific syntax](https://docs.getdbt.com/reference/resource-configs/grants#bigquery-examples))?

`dbt_project.yml`
```yaml
models:
  project_name_here:
    folder_name_containing_your_dataset_models:
      +grants:
            roles/bigquery.dataViewer: ['user:person_1@awesome.com', 'user:person_2@awesome.com']
```
