### ISSUE TITLE
[Regression] Profile no longer accepts staging_bucket in execution_config

### ISSUE THREAD

**Issue by nickozilla** [dbt-labs/dbt-bigquery#743]
### Is this a regression in a recent version of dbt-bigquery?

- [X] I believe this is a regression in dbt-bigquery functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

When running a python model, I am unable to use the profile parameter `staging_bucket` which lives under:

dataproc_batch:
  environment_config:
    execution_config:
      staging_bucket: "gs:..."

& presents this error:

```
Unable to parse dataproc_batch as valid batch specification. See https://cloud.google.com/dataproc-serverless/docs/reference/rpc/google.cloud.dataproc.v1#google.cloud.dataproc.v1.Batch. Failed to parse environment_config field: Failed to parse execution_config field: Message type "google.cloud.dataproc.v1.ExecutionConfig" has no field named "staging_bucket" at "Batch.environment_config.execution_config".
 Available Fields(except extensions): "['serviceAccount', 'networkUri', 'subnetworkUri', 'networkTags', 'kmsKey']"..
```

As far as I can tell this is still the place where this parameter should live - https://github.com/googleapis/python-dataproc/blob/main/google/cloud/dataproc_v1/types/shared.py#L222

This was first noticed today after I built a new container with `dbt-core==1.5.1` so I'm not sure if the issue is due to that, or a back ported fix onto `dbt-bigquery==1.5.1`

### Expected/Previous Behavior

Previously the same profile was correctly parsing the parameter and using the staging_bucket correctly. The default behaviour doesnt work for my use case, as the service account that runs dbt in dataproc is only directly permissioned against the specific bucket.

### Steps To Reproduce

Dependencies:
dbt-core==1.5.1
dbt-bigquery==1.5.1

Profile:
```
modelling:
  target: dev
  outputs:
    dev:
      dataset: dev
      job_execution_timeout_seconds: 2000
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: "{{ env_var('PROJECT_ID') }}"
      threads: 8
      type: bigquery
      dataproc_region: europe-west1
      gcs_bucket: "{{ env_var('PYTHON_DBT_MODELS_BUCKET') }}"
      dataproc_batch:
        environment_config:
          execution_config:
            service_account: "{{ env_var('SERVICE_ACCOUNT') }}"
            subnetwork_uri: "{{ env_var('SUBNET') }}"
            staging_bucket: "{{ env_var('PYTHON_DBT_STAGING_BUCKET') }}"
        pyspark_batch:
          jar_file_uris:
            [
              "gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.13-0.29.0.jar",
            ]
        runtime_config:
          container_image: "europe-docker.pkg.dev/{{ env_var('PYTHON_DBT_CONTAINER') }}"
```

& then run any python model with`dbt run --select python_model`

### Environment

```markdown
- OS: Linux version 5.15.49-linuxkit (root@buildkitsandbox) (gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, GNU ld (GNU Binutils) 2.35.2) #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022
- Python: 3.10
- dbt-core (working version): 1.5.0
- dbt-bigquery (working version): 1.5.1
- dbt-core (regression version): 1.5.1
- dbt-bigquery (regression version): 1.5.1
```
