### ISSUE TITLE
BigQuery ProjectID 

### ISSUE THREAD

**Issue by denimalpaca** [dbt-labs/dbt-bigquery#76]
### Describe the bug
Ran `dbt test` with Big Query as the connection using Airflow, and got an Error on the custom test. All standard dbt tests worked fine.
Error message:
`[2021-11-29, 17:33:46 UTC] {subprocess.py:89} INFO -   Invalid project ID 'simple_bigquery_example_dag.[correct-project-id-here-redacted]'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.`

Seems like the dataset name from the test's SQL query got prepended to the project ID name.
SQL Query:
`SELECT * FROM simple_bigquery_example_dag.forestfires`

Schema:
```

version: 2

models:
  - name: forestfire_test
    description: "A dbt model of forestfire data."
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - not_null
          - unique
      - name: month
        tests:
          - not_null
          - accepted_values:
              values: ['aug', 'mar', 'sep']
      - name: ffmc
        tests:
          - ffmc_value_check
```

Where `ffmc_value_check` is the failing test.

Query for the test:
```
{% test ffmc_value_check(model, column_name) %}

SELECT {{ column_name }}
FROM simple_bigquery_example_dag.{{ model }}
HAVING NOT({{ column_name }} >= 90)

{% endtest %}
```

### Steps To Reproduce
The DAG from this pull request can be used to replicate the error:
https://github.com/astronomer/airflow-data-quality-demo/pull/9

Steps:
- Insert forest fire data into BigQuery in a dataset and table: `simple_bigquery_example_dag.forestfire_test` (this can also be done by running the BigQuery example DAG [here](https://github.com/astronomer/airflow-data-quality-demo/blob/main/dags/bigquery_examples/simple_bigquery_el.py)).
- Run the dbt test command from the PR linked above

### Expected behavior
Test is expected to Fail, not to Error. Project ID is not expected to have the `simple_bigquery_example_dag.` prefix.

### Screenshots and log output

<img width="1770" alt="Screen Shot 2021-11-29 at 1 07 54 PM" src="https://user-images.githubusercontent.com/2653551/143920535-a6931363-fbc6-4dc9-ad32-176ad69314f3.png">

### System information
**The output of `dbt --version`:**
```
dbt==0.21.0
```

**The operating system you're using:**
MacOS with Docker

**The output of `python --version`:**
python 3.9
