### ISSUE TITLE
[ADAP-621] [Bug] impersonate_service_account and job_execution_timeout_seconds

### ISSUE THREAD

**Issue by cmc333333** [dbt-labs/dbt-bigquery#769]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When setting `impersonate_service_account` along with a high (>1 hr) `job_execution_timeout_seconds`, the BQ API gives us an error:
> Access tokens for service account [service account email here] can not have lifetimes of more than 1 hour. Use the Org Policy Constraint constraints/iam.allowServiceAccountCredentialLifetimeExtension to allow up to 12 hours.

The credentials shouldn't need to live the whole hour+, however, since they can be re-generated whenever making a new BQ call.[](url)

### Expected Behavior

A high `job_execution_timeout_seconds` would be compatible with `impersonate_service_account` without needing to adjust org policy constraints.

### Steps To Reproduce

1. Set up service account impersonation per [this doc](https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup#service-account-impersonation)
2. Add a three hour timeout (using `timeout_seconds` rather than `job_execution_timeout_seconds` to match our actual config)
```
my-profile:
  target: airflow
  outputs:
    airflow:
      type: bigquery
      method: oauth
      impersonate_service_account: "{{ env_var('DBT_SA_EMAIL') }}"
      project: "{{ env_var('DBT_PROJECT') }}"
      dataset: "dbt"
      retries: 3
      threads: 10
      timeout_seconds: 10800 # 3 hours
      location: US
      priority: interactive
```
3. Try to run that target. See an error

### Environment

```markdown
- OS: Debian GNU/Linux 11 (bullseye)
- Python: Python 3.9.16
- dbt-core: 1.5.1
- dbt-bigquery: 1.5.1
```

### Additional Context

We're trying to switch away from `keyfile_json`, where we first specified the three hour limit.
