### ISSUE TITLE
[ADAP-767] [Bug] Model's contact validation fails on query data types change

### ISSUE THREAD

**Issue by dementiev27** [dbt-labs/dbt-bigquery#861]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Model data types are being detected incorrectly due to empty query caching in BigQuery, resulting in contract validation errors.

To get column data types, DBT executes a query like this:

```sql
select * from (
    -- model's body goes here
    select
        id,
        amount
    from project.dataset.payments
    --
) as __dbt_sbq
where false
limit 0
```

This query is cached in BigQuery, leading to incorrect data types detection in case of their change.

### Expected Behavior

Model data types are detected correctly and contract validation works as expected.

### Steps To Reproduce

1. Create a model that selects data from any table:
```sql
select
    customer_id,
    sum(amount) as total_amount
from {{ source('finance', 'payments') }}
where finished is true
group by customer_id
```

```yaml
version: 2

models:
  - name: customer_payments
    config:
      contract:
        enforced: true
    columns:
      - name: customer_id
        data_type: string
      - name: total_amount
        data_type: integer

```
2. Run this model. Under the hood, DBT will execute the "empty" query mentioned earlier.
3. Change the `customer_id` data type in the `payments` source table.
Also, appropriately change the data type of `customer_id` for the model in the YAML config.
4. Run the model again. The dbt will not detect the `customer_id` data type change, and you will get the error:

```
This model has an enforced contract that failed.
Please ensure the name, data_type, and number of columns in your contract match the columns in your model's definition.
| column_name | definition_type | contract_type | mismatch_reason    |
| ----------- | --------------- | ------------- | ------------------ |
| customer_id | INT64           | STRING        | data type mismatch |
```

### Environment

```markdown
- OS: macOS 13.4.1
- Python: 3.10.2
- dbt-core: 1.5.2
- dbt-bigquery: 1.5.3
```
