### ISSUE TITLE
Labels are not working as intended 

### ISSUE THREAD

**Issue by minhajpasha** [dbt-labs/dbt-bigquery#893]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

dbt_project.yml

models:
    dbt_project: 
        +persist_docs:
            relation: true
            columns: true
        +labels:
            created_by: dbt
        staging:
            +labels:
                layer: staging 
            +enabled: true
            +materialized: table
        primary:
            +labels:
                layer: primary 
            +enabled: true
            +materialized: table

All the staging tables should be labelled as : created_by: dbt  & layer: staging 
All the primary tables should be labelled as : created_by: dbt  & layer: primary 

but it's getting labeled as below
<img width="500" alt="image" src="https://github.com/dbt-labs/dbt-bigquery/assets/92152711/4a626e14-e8d4-4bc0-a15a-59e3ae2cee6a">

### Expected Behavior

The labels should be as below:
<img width="500" alt="image" src="https://github.com/dbt-labs/dbt-bigquery/assets/92152711/e3810f79-e793-4e89-b125-c92eef34ead8">

### Steps To Reproduce

I have checked on dbt 1.5.3 version

run the models under models/staging and models/primary folder(dbt run)

### Environment

```markdown
- OS:Mac
- Python:3.8
- dbt-core:1.5.3
- dbt-bigquery:1.5.3
```

**Comment by dbeatty10** [comment]
Thanks for reaching out @minhajpasha !

I think what you described is expected behavior for `labels`, but I'm guessing you're expecting it to behave like `grants`. 

See [here](https://docs.getdbt.com/reference/configs-and-properties#combining-configs) for the general overview of "clobber" vs. "add" behavior for a few configs that take collections like lists or dictionaries as input:

> Most configurations are "clobbered" when applied hierarchically. Whenever a more-specific value is available, it will completely replace the less-specific value. Note that a few configs have different merge behavior:
> 
> - [`tags`](https://docs.getdbt.com/reference/tags) are additive. If a model has some tags configured in `dbt_project.yml`, and more tags applied in its `.sql` file, the final set of tags will include all of them.
> - [`meta`](https://docs.getdbt.com/reference/resource-configs/meta) dictionaries are merged (a more specific key-value pair replaces a less specific value with the same key)
> - [`pre-hook` and `post-hook`](https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook) are also additive.

See the paragraph at the bottom of [this](https://docs.getdbt.com/reference/resource-configs/plus-prefix) page for a quick explanation of the uniqueness of `grants`:

> **Note**: This use of the `+` prefix, in `dbt_project.yml`, is distinct from the use of `+` to control config merge behavior (clobber vs. add) in other config settings (specific resource `.yml` and `.sql` files). Currently, the only config which supports `+` for controlling config merge behavior is [`grants`](https://docs.getdbt.com/reference/resource-configs/grants#grant-config-inheritance).

### Workaround

List out **all** the entire dictionary of desired key/value pairs whenever (re-)defining the `labels` config, like below:

```yaml
models:
    dbt_project: 
        +persist_docs:
            relation: true
            columns: true
        +labels:
            created_by: dbt
        staging:
            +labels:
                created_by: dbt
                layer: staging 
            +enabled: true
            +materialized: table
        primary:
            +labels:
                created_by: dbt
                layer: primary 
            +enabled: true
            +materialized: table
```

### Summary

Since this is expected behavior, I'm going to recategorize this as a feature request. Since there's a known workaround and we're not currently planning on changing it, I'm going to close this as "not planned".
