### ISSUE TITLE
[ADAP-954] [Bug] Missing container package for dbt-bigquery-1.6.7

### ISSUE THREAD

**Issue by tavneet-s** [dbt-labs/dbt-bigquery#975]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The last package in the container registry is for [dbt-bigquery-1.6.6](https://github.com/dbt-labs/dbt-bigquery/pkgs/container/dbt-bigquery). Since dbt-bigquery-1.6.7 was released on October 9, which fixes the labels issue , our team was upgrading it on a high priority. If this image can be pushed to the container registry, it will  unblock our update process. 

### Expected Behavior

I expect to be able to use the latest container image (dbt-bigquery-1.6.7) for in Cloud run on GCP and update our CI/CD pipeline. 

### Steps To Reproduce

My cloud build.yaml 
```yaml
steps:
  - name: 'ghcr.io/dbt-labs/dbt-bigquery:1.6.7'
    args:
      - docs
      - generate
      - '--target-path'
      - .
      - '--project-dir'
      - ../../environment/development/team/
      - '--profiles-dir'
      - ../../environment/development/team/
    dir: docs/data_systems/
    entrypoint: dbt
options:
  logging: CLOUD_LOGGING_ONLY
```

<img width="1006" alt="Screenshot 2023-10-23 at 19 31 23" src="https://github.com/dbt-labs/dbt-bigquery/assets/124144925/f5243c9e-8b1a-4c25-a6fe-129bd2a52718">

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-bigquery:
```
