### ISSUE TITLE
[CT-3307] `hours_to_expiration` ignored in py-dbt

### ISSUE THREAD

**Issue by gbmarc1** [dbt-labs/dbt-bigquery#999]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have the following config in `dbt_project.yml`. The Bigquery table that is created using `py-dbt` does not have an expiration time (see image below). The model created usin `sql` has an expiration time.

```yml
models:
    nsfw:
      +hours_to_expiration: "{{ '24' if target.name=='ci' else None }}"
      +enabled: true
      +schema: nsfw
      +persist_docs:
        relation: true
        columns: true
```
![image](https://github.com/dbt-labs/dbt-core/assets/29891099/5e4982e2-a8ff-4535-b4db-ca684987b98b)
![image](https://github.com/dbt-labs/dbt-core/assets/29891099/ed95c14d-8f41-4c43-9a20-9cfcd1ee8851)

### Expected Behavior

The Bigquery table that is created using `py-dbt` should also have an expiration time.

### Steps To Reproduce

See above

### Environment

```markdown
- OS: macos
- Python 3.11.1
- dbt: 1.6.6
```

### Which database adapter are you using with dbt?

Bigquery
